#!/bin/bash
compiler=$1
optimization=$2

$compiler -$optimization -march=native -c kernels/math/Math.f90
$compiler -$optimization -march=native -c kernels/math/Clebsch_Legendre.f90
$compiler -$optimization -march=native -c kernels/math/SphericalFunctions.f90
$compiler -$optimization -march=native -c kernels/math/Vector_analysis.f90
$compiler -$optimization -march=native -c kernels/math/FFT.f90
$compiler -$optimization -march=native -c kernels/math/Harmsy.f90

$compiler -$optimization -march=native -c code/ice/IceConstants.f90

$compiler -$optimization -march=native -c output/Paths.f90
$compiler -$optimization -march=native -c output/OutputMod.f90

$compiler -$optimization -march=native -c output/ice/mod/OutputIceMod.f90

$compiler -$optimization -march=native output/ice/ConvergenceIce.f90 *.o -o code_out

rm -f curveShape_dn.dat curveShape_up.dat curveTopo_dn.dat curveTopo_up.dat || true
#./code_out
rm code_out *.o *.mod