#!/bin/bash
###########################################################################################
####                              POSSIBLE CODE SETTINGS                               ####
####    ocean_convection, ice_ocean, ocean_tides, ice_deformation, ice_convergence     ####
###########################################################################################
code_type="ocean_convection"

###########################################################################################
####                              COMPILER SET UP                                      ####
###########################################################################################
compile="gfortran-12 -Ofast \
                     -march=native \
                     -fno-bounds-check \
                     -flto=auto \
                     -fwhole-program \
                     -fopenmp"

###########################################################################################
####                             COMPILATION OF THE BASELINE                           ####
###########################################################################################
$compile -c kernels/math/math.f90
$compile -c kernels/math/sph/sph_norms.f90
$compile -c output/mod/Paths.f90
$compile -c output/mod/OutputMod.f90

rm -f temp_averaged.spec velc_averaged.spec flux_averaged.spec || true
rm -f curveShape_dn.dat curveShape_up.dat curveTopo_dn.dat curveTopo_up.dat || true

###########################################################################################
####                                    LINKING                                        ####
###########################################################################################
case $code_type in
    
    ocean_convection)
        $compile -c code/ocean/ocean_constants.f90
        $compile output/OutputOcean.f90 *.o -o code_out
        ./code_out
    ;;
    
    ocean_tides)
        $compile -c code/ocean/ocean_constants.f90
        $compile output/OutputOcean.f90 *.o -o code_out
        ./code_out
    ;;
    
    ice_ocean)
        $compile -c code/ocean/ocean_constants.f90
        $compile output/OutputOcean.f90 *.o -o code_out
        ./code_out
        
        $compile -c code/ice/ice_constants.f90
        $compile output/OutputIce.f90 *.o -o code_out
        ./code_out
    ;;
    
    ice_deformation)
        $compile -c code/ice/ice_constants.f90
        $compile output/OutputIce.f90 *.o -o code_out
        ./code_out
    ;;
    
    ice_convergence)
        $compile -c code/ice/ice_constants.f90
        $compile output/ConvergenceIce.f90 *.o -o code_out
        ./code_out
    ;;
    
esac

###########################################################################################
####                                    CLEANING                                       ####
###########################################################################################
rm *.mod *.o code_out