#!/bin/bash
compiler=gfortran-12
optimization=Ofast

#ladova kora
#./output/scripts/getConvIce $compiler $optimization
./output/scripts/getDataIce $compiler $optimization
#./output/scripts/gmtIce

#ocean
./output/scripts/getDataOcean $compiler $optimization
#./output/scripts/gmtOcean
