#!/bin/bash
###########################################################################################
####                              COMPILER SET UP                                      ####
###########################################################################################
compile="gfortran-12 -Ofast -march=native -flto=auto -fwhole-program -fopenmp"

###########################################################################################
####                              POSSIBLE CODE SETTINGS                               ####
####       test_speed, ocean_convection, ice_ocean, ocean_tides, ice_deformation       ####
###########################################################################################
code_type="ice_deformation"

###########################################################################################
####                    COMPILATION OF THE BASELINE, DIRS SET UP                       ####
###########################################################################################
$compile -c kernels/math/Math.f90
$compile -c kernels/math/math1/*.f90
$compile -c kernels/math/sph/*.f90

$compile -c kernels/math/mathsphsvt/Sphsvt.f90
$compile -c kernels/math/mathsphsvt/smod/*.f90

$compile -c kernels/math/fft/Fourier_transform.f90
$compile -c kernels/math/fft/smod/*.f90

$compile -c kernels/math/lu_matrix/Matrix.f90
$compile -c kernels/math/lu_matrix/smod/*.f90

$compile -c kernels/grid/radial/RadialGrid.f90
$compile -c kernels/grid/radial/smod/*.f90

$compile -c kernels/grid/spherical/SphericalHarmonics.f90
$compile -c kernels/grid/spherical/smod/*.f90

$compile -c kernels/equations/solutions/Solution.f90
$compile -c kernels/equations/solutions/smod/*.f90

$compile -c kernels/equations/matrices/Matrices.f90
$compile -c kernels/equations/matrices/smod/*.f90

$compile -c kernels/gmodel/Gravity.f90
$compile -c kernels/gmodel/smod/*.f90

$compile -c kernels/mparams/Mparams.f90
$compile -c kernels/mparams/smod/*.f90

$compile -c kernels/boundaries/Boundaries.f90
$compile -c kernels/boundaries/smod/*.f90

$compile -c kernels/object/PhysicalObject.f90
$compile -c kernels/object/smod/*.f90
$compile -c kernels/object/smod/Matrices/*.f90
$compile -c kernels/object/smod/NonLinearTerms/*.f90
$compile -c kernels/object/smod/Solvers/*.f90
$compile -c kernels/object/smod/Variables/*.f90
$compile -c kernels/object/smod/Material_parameters/*.f90
$compile -c kernels/object/smod/Forces/*.f90
$compile -c kernels/object/smod/Output/*.f90
$compile -c kernels/object/smod/Balances/*.f90

$compile -c code/ocean/OceanConstants.f90
$compile -c code/ocean/OceanMod.f90
$compile -c code/ocean/mod/*.f90

$compile -c code/ice/Ice_parameters/*.f90
$compile -c code/ice/IceConstants.f90

$compile -c code/ice/IceMod/IceMod.f90
$compile -c code/ice/IceMod/smod/*.f90

$compile -c code/ice/IceTides/IceTidesMod.f90
$compile -c code/ice/IceTides/smod/*.f90

$compile -c code/ice/IceCrust/IceCrustMod.f90
$compile -c code/ice/IceCrust/smod/*.f90

rm -r -f data || true

###########################################################################################
####                                    LINKING                                        ####
###########################################################################################
case $code_type in
    
    test_legendre)
        $compile code/codes/BielyKralik_legeTest.f90 *.o -o Test_lege
    ;;

    test_speed)
        mkdir data
        
        mkdir data/data_ocean_temp
        mkdir data/data_ocean_veloc
        mkdir data/data_ocean_flux
        
        $compile code/codes/BielyKralik_speedTest.f90 *.o -o Test_speed
    ;;
    
    ocean_convection)
        mkdir data

        mkdir data/data_ocean_temp
        mkdir data/data_ocean_veloc
        mkdir data/data_ocean_flux
        
        $compile code/codes/BielyKralik_oceanConv.f90 *.o -o Test_convection
    ;;
    
    ice_ocean)
        mkdir data
        
        mkdir data/data_ice_topo
        mkdir data/data_ice_shape
        mkdir data/data_ice_tides
        
        mkdir data/data_ocean_temp
        mkdir data/data_ocean_veloc
        mkdir data/data_ocean_flux
        
        $compile code/codes/BielyKralik_oceanIce.f90 *.o -o Test_oceanIce
    ;;
    
    ocean_tides)
        mkdir data

        mkdir data/data_ocean_veloc
    
        $compile code/codes/BielyKralik_tidesOcean.f90 *.o -o Test_tides
    ;;
    
    ice_deformation)
        mkdir data

        mkdir data/data_ice_topo
        mkdir data/data_ice_shape
        mkdir data/data_ice_tides
        
        $compile code/codes/BielyKralik_Ice.f90 *.o -o Test_ice
    ;;
    
esac

###########################################################################################
####                                    CLEANING                                       ####
###########################################################################################
rm *.smod *.mod *.o
