#!/bin/bash
###########################################################################################
####                              POSSIBLE CODE SETTINGS                               ####
####    ocean_convection, ice_ocean, ocean_tides, ice_deformation, ice_convergence     ####
###########################################################################################
code_type="ocean_convection"

###########################################################################################
####                               INSTRUCTIONS SET UP                                 ####
####                                avx, avx2, avx512                                  ####
###########################################################################################
instructions="avx2"

###########################################################################################
####                                 COMPILER SET UP                                   ####
###########################################################################################
fcompile="gfortran-12 -Ofast \
                      -march=native \
                      -fno-bounds-check \
                      -flto=auto \
                      -fwhole-program \
                      -fopenmp \
                      -D$instructions \
                      -cpp"

###########################################################################################
####                             COMPILATION OF THE BASELINE                           ####
###########################################################################################
$fcompile -c kernels/math/processor/alignement.f90
$fcompile -c kernels/math/math/math.f90
$fcompile -c kernels/math/math/smod/math@conversions.f90
$fcompile -c kernels/math/sph/sph_norms.f90
$fcompile -c output/mod/Paths.f90
$fcompile -c output/mod/OutputMod.f90

rm -f temp_averaged.spec velc_averaged.spec flux_averaged.spec || true
rm -f curveShape_dn.dat curveShape_up.dat curveTopo_dn.dat curveTopo_up.dat || true

###########################################################################################
####                                    LINKING                                        ####
###########################################################################################
case $code_type in
    
    ocean_convection)
        $fcompile -c code/ocean/ocean_constants.f90
        $fcompile output/OutputOcean.f90 *.o -o code_out
    ;;
    
    ocean_tides)
        $fcompile -c code/ocean/ocean_constants.f90
        $fcompile output/OutputOcean.f90 *.o -o code_out
        ./code_out
    ;;
    
    ice_ocean)
        $fcompile -c code/ocean/ocean_constants.f90
        $fcompile output/OutputOcean.f90 *.o -o code_out
        ./code_out
        
        $fcompile -c code/ice/ice_constants.f90
        $fcompile output/OutputIce.f90 *.o -o code_out
        ./code_out
    ;;
    
    ice_deformation)
        $fcompile -c code/ice/ice_constants.f90
        $fcompile output/OutputIce.f90 *.o -o code_out
        ./code_out
    ;;
    
    ice_convergence)
        $fcompile -c code/ice/ice_constants.f90
        $fcompile output/ConvergenceIce.f90 *.o -o code_out
        ./code_out
    ;;
    
esac

###########################################################################################
####                                    CLEANING                                       ####
###########################################################################################
rm *.mod *.o *.smod
