#!/bin/bash 
###########################################################################################
####                              COMPILER SET UP                                      ####
###########################################################################################
compile="gfortran-12 -Ofast -march=native -frename-registers -flto=auto -fopenmp"

###########################################################################################
####                              POSSIBLE CODE SETTINGS                               ####
###########################################################################################
code_ice="ice"
code_convection="convection"
code_tides="tides"
code_oceanIce="iceOcean"
code_test="speed"

code_type="speed"

###########################################################################################
####                    COMPILATION OF THE BASELINE, DIRS SET UP                       ####
###########################################################################################
$compile -c kernels/math/Math.f90
$compile -c kernels/math/Conversions.f90
$compile -c kernels/math/Clebsch_Gordan.f90
$compile -c kernels/math/FFT.f90
$compile -c kernels/math/SphericalFunctions.f90
$compile -c kernels/math/poly_lege.f90
$compile -c kernels/math/sph_vectors.f90

$compile -c kernels/grid/radial/RadialGrid.f90
$compile -c kernels/grid/radial/smod/*.f90

$compile -c kernels/grid/spherical/SphericalHarmonics.f90
$compile -c kernels/grid/spherical/smod/*.f90

$compile -c kernels/equations/solutions/Solution.f90
$compile -c kernels/equations/solutions/smod/*.f90

$compile -c kernels/equations/matrix/Matrix.f90
$compile -c kernels/equations/matrix/smod/*.f90

$compile -c kernels/equations/matrices/Matrices.f90
$compile -c kernels/equations/matrices/smod/*.f90

$compile -c kernels/gmodel/Gravity.f90
$compile -c kernels/gmodel/smod/*.f90

$compile -c kernels/object/PhysicalObject.f90
$compile -c kernels/object/smod/*.f90

rm -r -f data || true
mkdir data

###########################################################################################
####                               OCEAN-ICE COMPUTATION                               ####
###########################################################################################
if [ "$code_type" = "$code_oceanIce" ]; then
mkdir data/data_ice_topo
mkdir data/data_ice_shape
mkdir data/data_ice_tides

mkdir data/data_ocean_temp
mkdir data/data_ocean_veloc
mkdir data/data_ocean_flux

$compile -c code/ocean/OceanConstants.f90
$compile -c code/ocean/OceanMod.f90
$compile -c code/ocean/mod/OceanIceMod.f90

$compile -c code/ice/IceConstants.f90
$compile -c code/ice/IceViscosity.f90
$compile -c code/ice/IceMod.f90
$compile -c code/ice/smod/*.f90
$compile -c code/ice/mod/IceTidesMod.f90
$compile -c code/ice/mod/IceCrustMod.f90

$compile code/codes/BielyKralik_oceanIce.f90 *.o -o Test_oceanIce
fi

###########################################################################################
####                            OCEAN TIDES COMPUTATION                                ####
###########################################################################################
if [ "$code_type" = "$code_tides" ]; then
$compile -c code/ocean/OceanConstants.f90
$compile -c code/ocean/OceanMod.f90
$compile -c code/ocean/mod/OceanTidesMod.f90

$compile code/codes/BielyKralik_tidesOcean.f90 *.o -o Test_tides
fi

###########################################################################################
####                                   SPEED TEST                                      ####
###########################################################################################
if [ "$code_type" = "$code_test" ]; then
mkdir data/data_ocean_temp
mkdir data/data_ocean_veloc
mkdir data/data_ocean_flux

$compile -c code/ocean/OceanConstants.f90
$compile -c code/ocean/OceanMod.f90
$compile -c code/ocean/mod/OceanConvMod.f90

$compile code/codes/BielyKralik_speedTest.f90 *.o -o Test_speed
fi

###########################################################################################
####                              CONVECTION COMPUTATION                               ####
###########################################################################################
if [ "$code_type" = "$code_convection" ]; then
mkdir data/data_ocean_temp
mkdir data/data_ocean_veloc
mkdir data/data_ocean_flux

$compile -c code/ocean/OceanConstants.f90
$compile -c code/ocean/OceanMod.f90
$compile -c code/ocean/mod/OceanConvMod.f90

$compile code/codes/BielyKralik_oceanConv.f90 *.o -o Test_convection
fi

###########################################################################################
####                          ICE DEFORMATION COMPUTATION                              ####
###########################################################################################
if [ "$code_type" = "$code_ice" ]; then
mkdir data/data_ice_topo
mkdir data/data_ice_shape
mkdir data/data_ice_tides

$compile -c code/ice/IceConstants.f90
$compile -c code/ice/IceViscosity.f90
$compile -c code/ice/IceMod.f90
$compile -c code/ice/smod/*.f90
$compile -c code/ice/mod/IceTidesMod.f90
$compile -c code/ice/mod/IceCrustMod.f90

$compile code/codes/BielyKralik_Ice.f90 *.o -o Test_ice
fi

###########################################################################################
####                                    CLEANING                                       ####
###########################################################################################
rm *.smod *.mod *.o
