#!/bin/bash
#Kubo von Kvorkenstein, 2022
compiler=gfortran-12
optimization=Ofast

$compiler -$optimization -march=native -c kernels/code_base_line/math/Math.f90
$compiler -$optimization -march=native -c output/ice/mod/ConvergenceCurveMod.f90      #vypocet casovej rady L2 norm
$compiler -$optimization -march=native output/ice/ConvergenceIce.f90 *.o -o code_out  #hlavny program        

rm -f curveShape.dat curveTopo.dat curveFlux.dat || true
./code_out
rm code_out *.o *.mod