#!/bin/bash
compiler=$1
optimization=$2

$compiler -$optimization -march=native -c kernels/code_base_line/math/Math.f90
$compiler -$optimization -march=native -c output/Paths.f90
$compiler -$optimization -march=native -c output/ice/mod/ConvergenceCurveMod.f90
$compiler -$optimization -march=native output/ice/ConvergenceIce.f90 *.o -o code_out

rm -f curveShape.dat curveTopo.dat curveFlux.dat || true
##./code_out
rm code_out *.o *.mod