#!/bin/bash
compiler=$1
optimization=$2

$compiler -$optimization -march=native -c kernels/code_base_line/math/Math.f90    #nepostradatelne matematicke konstanty
$compiler -$optimization -march=native -c code/ice/IceConstants.f90               #konstanty riadiace vypocet v ladovej kore
$compiler -$optimization -march=native -c output/modules/fft/FFT.f90              #Fourierova transformacia
$compiler -$optimization -march=native -c output/modules/mod/OutputMod.f90        #obecny modul

$compiler -$optimization -march=native -c output/Paths.f90
$compiler -$optimization -march=native -c output/ice/mod/OutputIceMod.f90         #generovanie suborov tvaru a topografie
$compiler -$optimization -march=native output/ice/OutputIce.f90 *.o -o code_out   #topografia a tvar

./code_out
rm code_out *.o *.mod