#!/bin/bash
#Kubo von Kvorkenstein, 2022
source load_gmt4

plot () {
typeset -i max_value=$(cat $1)
typeset -i min_value=$(cat $2)
typeset -i cnt_value=$(cat $3)

makecpt -Cno_green -T$min_value/$max_value/0.01 > g.cpt
xyz2grd $4 -Ggeoid.grd -R0/360/-90/90 -Ddegree/degree/M/1/0/=/= -I1.
grdsample geoid.grd -Ggeoid.grd2 -R0/360/-90/90 -I1.
grdimage geoid.grd2 -R -JW180/12 -Cg.cpt -P -B -V -K -X2.5 -Y8 > fig.ps
grdcontour geoid.grd2 -R -JW180/12 -C$cnt_value -A$cnt_value -Gd4 -Ba30g30 -K -O >> fig.ps
pstext -R0/220/0/220 -Jx0.07/0.07  -X -Y -O -G0 -V << END >> fig.ps
END

ps2pdf fig.ps fig.pdf
pdfcrop fig.pdf $5
rm -f geoid* fig* g.cpt $1 $2 $3 
}

plot ice_ranges_Shape_dn_max ice_ranges_Shape_dn_min ice_ranges_Shape_dn_cnt Shape-dn.dat Shape-dn.pdf
plot ice_ranges_Shape_up_max ice_ranges_Shape_up_min ice_ranges_Shape_up_cnt Shape-up.dat Shape-up.pdf
plot ice_ranges_Topo_dn_max ice_ranges_Topo_dn_min ice_ranges_Topo_dn_cnt Topo-dn.dat Topo-dn.pdf
plot ice_ranges_Topo_up_max ice_ranges_Topo_up_min ice_ranges_Topo_up_cnt Topo-up.dat Topo-up.pdf